### ISSUE TITLE
Running the FTM seems to give a different result than the result in the playground

### ISSUE THREAD

**Issue by uvafan** [epoch-research/ftm#8]
I followed the instructions in the README, and the results looked like 
<img width="934" alt="image" src="https://github.com/epoch-research/ftm/assets/13226774/2e50e621-9b52-4473-a0ee-b0ccca89e234">

On https://takeoffspeeds.com/playground.html , the best-guess scenario has full economic automation 4 years earlier. What explains the difference (I checked some of the parameters and they seemed the same)

**Comment by eirol** [comment]
Ooopsi. Good catch!

The problem was that the takeoffspeeds.com version has the runtime-training tradeoff enabled by default, while the Python version had it disabled.

I have enabled the tradeoff  in the Python version (see the [new spreadsheet](https://docs.google.com/spreadsheets/d/1OMBcEvWgCVut305CRBPxLtxjxVP4m_DOiMu9qDUgHso/edit#gid=0&range=E8)) and now there's no difference.

**Comment by uvafan** [comment]
Thanks. Btw, that spreadsheet isn't the one linked in the README

**Comment by eirol** [comment]
Ooops. Thanks, fixed.
